pygments: true
permalink: /:year/:month/:day.html
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis","hard_wrap", "fenced_code_blocks", "autolink", "tables", "superscript", "strikethrough", "lax_spacing"]